project:
  type: website

website:
  title: "SP2023"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/guebin/SP2023
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
  sidebar:
    style: "docked"
    search: true
    contents: auto
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true